import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<title>VPN</title>
			<link
				rel='icon'
				type='image/svg+xml'
				href='https://www.pngarts.com/files/1/Globe-PNG-Download-Image.png'
			/>
			<body>{children}</body>
		</html>
	)
}
